### ISSUE TITLE
Linking with Xamarin.Android libraries fails

### ISSUE THREAD

**Issue by Eeedgar** [jguertl/SharePlugin#45] opened 2017-02-28 19:52 UTC
When trying to compile in Release mode with Xamarin.Android.Support.CustomTabs.CustomTabsIntent v25.1.1, the following error occurs:

Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'System.Void Android.Support.CustomTabs.CustomTabsIntent::LaunchUrl(Android.App.Activity,Android.Net.Uri)' (defined in assembly 'Plugin.Share, Version=5.0.1.8, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.Android.Support.CustomTabs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Android.Support.CustomTabs.CustomTabsIntent::LaunchUrl(Android.App.Activity,Android.Net.Uri)

**Comment by jamesmontemagno** [comment] 2017-02-28 19:57
Duplicate of #43

**Closed by jamesmontemagno** 2017-02-28 19:57 UTC

**Comment by kyluke** [comment] 2017-03-01 12:39
I see it's marked as a duplicate, I'm facing the same issue. Downgrading has caused other issues in my build for me that are taking long to fix. Any idea on when a new version supporting v25 will be out?

**Comment by jamesmontemagno** [comment] 2017-03-01 18:12
Try: 5.1.0.14-beta

**Comment by jamesmontemagno** [comment] 2017-03-02 05:57
6.1.0.19-beta is built against 25.1.1 and validated working in the test sample app on 25-1-1-support branch. 5.x will remain on 23.x support libraries

**Comment by Eeedgar** [comment] 2017-03-02 08:03
Thanks James!  Super fast - confirmed v6.1.0.19 works perfectly.  Thanks again
