### ISSUE TITLE
Share Popover Positioning on iOS Tablet

### ISSUE THREAD

**Issue by adamzucchi** [jguertl/SharePlugin#77] opened 2017-11-16 14:07 UTC
This is somewhat related to issue #54, but I am more interested in getting the ability to position the share popover on iOS tablets.  Currently the popover displayed in the upper top left corner of the tablet screen.

**Comment by jamesmontemagno** [comment] 2017-11-16 19:48
Yes, this is a duplicate of #54

**Closed by jamesmontemagno** 2017-11-16 19:48 UTC
