### ISSUE TITLE
Linker error regarding Xamarin.Android.Support.CustomTabs

### ISSUE THREAD

**Issue by brandonrisell** [jguertl/SharePlugin#44] opened 2017-02-27 21:34 UTC
When I build a release configuration of an app using the Share Plugin with the latest Xamarin.Android.Support.CustomTabs package I get:
```
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets:
Error: Error executing task LinkAssemblies:
error XA2006: Could not resolve reference to 'System.Void Android.Support.CustomTabs.CustomTabsIntent::LaunchUrl(Android.App.Activity,Android.Net.Uri)'
(defined in assembly 'Plugin.Share, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.Android.Support.CustomTabs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
When the scope is different from the defining assembly, it usually means that the type is forwarded.
```

I put together a quick reproduction of the issue here:
https://github.com/brandonrisell/PluginTest

The steps I used to reproduce it:
* Create a new Xamarin.Forms PCL project
* Add the Share Plugin nuget package
* _I added a button that triggered the share plugin, but this isn't needed_
* Update the `Xamarin.Android.Support.CustomTabs` package from version 23.3.0 to 25.1.1
  * EDIT: Downgraded a different project that has this package to 24.2.1 and it appears so far to not have any issues with the linker
* Change config to `Release`
* Build Android project

**Comment by jamesmontemagno** [comment] 2017-02-27 23:14
Don't update that package there is no need to. I will have to generate an update build, but it is tricky with Xamarin.Forms where some developers wont have that version.

**Comment by jamesmontemagno** [comment] 2017-02-27 23:15
Duplicate of #43

**Closed by jamesmontemagno** 2017-02-27 23:15 UTC

**Comment by jamesmontemagno** [comment] 2017-03-01 18:12
Try: 5.1.0.14-beta

**Comment by brandonrisell** [comment] 2017-03-02 00:49
Awesome, I'll check it out and let you know how it goes. Thanks James.

**Comment by jamesmontemagno** [comment] 2017-03-02 05:57
6.1.0.19-beta is built against 25.1.1 and validated working in the test sample app on 25-1-1-support branch. 5.x will remain on 23.x support libraries

**Comment by brandonrisell** [comment] 2017-03-02 14:53
Installed and working great, thank you so much James. You're such a hard working and motivating person, I really admire how much you do for the Xamarin community.
