### ISSUE TITLE
Release mode linker error XA2006

### ISSUE THREAD

**Issue by IlyaLavrov97** [jguertl/SharePlugin#40] opened 2017-02-09 07:45 UTC
Hi,
After packages update I attempted to create a release package with "Linking" option set to "Sdk Assemblies only" and got the following error:

`Error executing task LinkAssemblies: error XA2006: Could not resolve reference to 'System.Void Android.Support.CustomTabs.CustomTabsIntent::LaunchUrl(Android.App.Activity,Android.Net.Uri)' (defined in assembly 'Plugin.Share, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.Android.Support.CustomTabs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded.`

After that, I downgraded package to version 4.0.0 (because downgrade to version 4.4.0 didn't resolve my issue) and the problem disappeared. If I use Linking = none my problem disappear, but share package features don't work.

**Comment by jamesmontemagno** [comment] 2017-02-09 17:40
You may need to add a linkskip. I will try this out though and get back.

**Comment by SoloXCRacer** [comment] 2017-02-10 19:25
I started getting this error when I upgraded the `Xamarin.Android.Support.CustomTabs` nuget package to _v25.1.0_ in my DEBUG configuration with the linker to "Sdk Assemblies Only".

I was about to say a "me too" when I set linking to None and it resolving the issue.  However, I have an app with Multi-Dex enabled.  From Xamarin Studio, "Enable Multi-Dex" checkbox is checked.  But in Visual Studio 2017, I noticed the checkbox is unchecked.  So I checked it and my code now compiles.

However, performing a `CrossShare.Current.OpenBrowser(myUrl, myBrowserOptions)` throws the following exception:

```
System.MissingMethodException: Method 'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found.
```

Skipping the linking nor setting Linking to "None" will always throw the above exception.  My guess is that something changed in `Xamarin.Android.Support.CustomTabs` _v25.1.0_.

**Comment by jamesmontemagno** [comment] 2017-02-11 00:39
It is built against 23.3.0 so I would leave that installed. No real need to upgrade. Is there some requirement? @IlyaLavrov97 did you also upgrade the nuget?

**Comment by IlyaLavrov97** [comment] 2017-02-11 10:56
Yes I also upgrade CustomTabs package, but I can't downgrade that, because I need downgrade Support.v4 (what is not good in my case):

`Xamarin.Android.Support.v4 25.1.0' is not compatible with 'Xamarin.Android.Support.CustomTabs 23.3.0`

I can get CustomTabs package version 23.0.1.3 only when I delete this package and downgrade your package to version 4.0.2 or 4.0.0 and I can solve my problem in this way.

**Comment by jamesmontemagno** [comment] 2017-02-11 20:04
Ah, I see that makes some sense because the tooling changed there. I would stick with 4.0.2 for now then. I will create a new package, but is hard to build against newer packages because of Xamarin.Forms dependencies.

**Closed** 2017-02-11 20:27 UTC

**Comment by jamesmontemagno** [comment] 2017-02-11 20:36
Pushing out new beta of 5.0.1, can you test that out.

**Comment by SharpMobileCode** [comment] 2017-02-12 00:07
Thank you!  I'll give it a shot when I get home tomorrow.  Thanks!

**Comment by IlyaLavrov97** [comment] 2017-02-13 09:16
I upgraded to beta and CustomTabs package didn't upgrade. Now I can build release package. Thanks a lot!

**Comment by SharpMobileCode** [comment] 2017-02-13 15:03
In my specific case, I need the Xamarin Android Support v25.1.0 in order to fix a bug with scrolling a CollapsingToolbar inside a Coordinator layout (it was Googles fault it broke).  Because of this, it automatically upgrades the Xamarin.Android.Support.CustomTabs to v25.1.0 and am unable to downgrade it because of the dependency.  So when I perform a `CrossShare.Current.OpenBrowser(myUrl, myBrowserOptions)` it throws the following exception:

```
System.MissingMethodException: Method 'Android.Support.CustomTabs.CustomTabsIntent.LaunchUrl' not found.
```

What I may end up doing is downloading the source and fixing/referencing it locally.  Depending on the nature of the fix, would you consider a pull request if the solution is to reference CustomTabs v25.1.0?  Or if you know what the issue is, can you point me to the right direction?

Thanks!

**Comment by jamesmontemagno** [comment] 2017-02-13 17:51
I don't think Custom Tabs is dependent on anything else you should be able to install the specific version I used to build against 23.0.1.3 or whatever and it should work fine from your earlier testing.

Let me play around and perhaps see if I can do a pre-release package against that newer version, the issue though is developers using Xamarin.Forms and dependencies on 23.3.0

**Comment by SharpMobileCode** [comment] 2017-02-13 18:34
Understood and see the dilemma for Xamarin Forms user.  It looks like custom tabs are tied to specific versions of the Xamarin.Android.Support.Compat Nuget Package:

https://www.nuget.org/packages/Xamarin.Android.Support.CustomTabs/25.1.1

Unfortunately, I'm tied to the later versions of the Compat library because of a bug fix that Google release is in the newer versions.  I won't be able to downgrade because I need this bug fix.  This forces CustomTabs to upgrade itself to v25.1.0 and it won't let me downgrade because Support.CustomTabs requires ("=") v25.1.0 of Support.Compat (which I need).

**Comment by jamesmontemagno** [comment] 2017-02-13 21:20
Just don't update that package. Leave it alone and it will work fine. I tested it: 
[App17.zip](https://github.com/jguertl/SharePlugin/files/772435/App17.zip)

**Comment by SharpMobileCode** [comment] 2017-02-14 03:30
Thanks!  I looked at App17.zip and noticed in that VS I can "ignore dependencies" when updating Nuget Packages.  I was able to do this and install an older version of CustomTabs, like in your sample project.  However, I still received a compile error something along the lines of "Duplicate Zip Entries" for CustomTabs.  I suspect it has something to do with Multi-Dex or another dependency (my app is a lot more complex than the sample app).  

So what I ended up doing as pulling the source and re-compiling Plugin.Android to API 25 and using the lastest CustomTabs Nuget package. I then just placed a static reference to the new DLLs and it's working on my end.  I think this will get me going for now.

Thanks for the help and I appreciate it!

**Comment by kyluke** [comment] 2017-03-01 13:59
I'm facing the same issue. Downgrading has caused other issues in my build for me that are taking long to fix. Any idea on when a new version supporting v25 will be out?

**Comment by jamesmontemagno** [comment] 2017-03-01 18:12
Try: 5.1.0.14-beta

**Comment by ComplexVariable** [comment] 2017-03-01 19:26
I did, 
Release Mode => Linker option => None , **Every thing works.**
Release Mode => Linker option => SDK Assemblies only, **Not working**

**Comment by jamesmontemagno** [comment] 2017-03-02 01:14
what do you have installed?

**Comment by kyluke** [comment] 2017-03-02 05:18
@jamesmontemagno 5.1.0.14-beta doesn't seem to be available. Am I doing something wrong?

![bildschirmfoto 2017-03-02 um 07 16 00](https://cloud.githubusercontent.com/assets/1087345/23493969/4b102868-ff18-11e6-9912-91ed179a77e5.png)

**Comment by jamesmontemagno** [comment] 2017-03-02 05:33
I removed it because someone said it didn't work either

**Comment by kyluke** [comment] 2017-03-02 05:39
Cool, is this issue something that's being worked on though?

**Comment by jamesmontemagno** [comment] 2017-03-02 05:58
6.1.0.19-beta is built against 25.1.1 and validated working in the test sample app on 25-1-1-support branch. 5.x will remain on 23.x support libraries

**Comment by kyluke** [comment] 2017-03-02 06:00
Okay cool. Is that going to be released soon?

**Comment by SharpMobileCode** [comment] 2017-03-10 20:03
I can also confirm that 6.1.0.19-beta works for my specific scenario.  I no longer have to use a static reference to a custom build :)  Thanks James!

**Comment by kyluke** [comment] 2017-03-14 09:18
same, thanks James!

**Comment by khawtf** [comment] 2017-04-08 13:03
Confirm that the update to 6.1.0.19-beta works with Custom-Tabs 25.1.1

**Comment by gotfocus** [comment] 2017-06-01 12:48
late to the party but same here. spent days on this before I stumbled on this thread.  thanks!!!

**Comment by jamesmontemagno** [comment] 2017-06-01 14:51
I will be making this large drastic change soon so the stable requires the latest.

**Comment by 15mgm15** [comment] 2017-06-13 23:04
G I have updated to 6.1.0.19-beta but it keep crashing I suppose I will downgrade.

**Comment by nbaua** [comment] 2017-06-23 06:13
Hi Have Latest stable - 5.0.0 and tried beta version as well, however it keeps crashing, can you please suggest if I can resolve following error (This is with latest stable 5.0.0.0, however beta result in similar way),

`error XA2006: Could not resolve reference to 'System.Void Android.Support.CustomTabs.CustomTabsIntent::LaunchUrl(Android.App.Activity,Android.Net.Uri)' (defined in assembly 'Plugin.Share, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.Android.Support.CustomTabs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'`

Thanks

**Comment by jamesmontemagno** [comment] 2017-06-23 16:00
REad the comment above and use the pre-release

**Comment by ipsmobile** [comment] 2017-10-03 18:44
Hi,
I am trying to use Xamarin.Auth(1.5.0.3) with a standalone android app and am getting the same error. I have v23.3.0 version of CustomTabs and v4 library installed and I cannot upgrade them because my project's min supported OS Version is 4.1(API 16). Is there any way to get around this issue with my project configuration?

**Comment by jamesmontemagno** [comment] 2017-10-03 18:47
You must upgrade your nugets sorry.

They both support Version 4.1 without any issues.

**Comment by ipsmobile** [comment] 2017-10-03 18:55
I tried, but this is what I get : 
Could not install package 'Xamarin.Android.Support.CustomTabs 25.4.0.2'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v6.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by jamesmontemagno** [comment] 2017-10-03 19:01
https://blog.xamarin.com/mastering-android-support-libraries/

**Comment by ipsmobile** [comment] 2017-10-03 19:07
Got it. Thanks a lot James.
